### ISSUE TITLE
Uncaught TypeError: Cannot read property 'ctime' of undefined

### ISSUE THREAD

**Issue by itsgoingd** [underground-works/atom-php-namespace-monkey#2]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.28.0 x64
**Electron**: 2.0.3
**OS**: Mac OS X 10.13.5
**Thrown From**: [php-namespace-monkey](https://github.com/underground-works/atom-php-namespace-monkey) package 0.2.0

### Stack Trace

Uncaught TypeError: Cannot read property 'ctime' of undefined

```
At /Users/its/.atom/packages/php-namespace-monkey/lib/php-namespace-monkey.js:63

TypeError: Cannot read property 'ctime' of undefined
    at /Users/its/Projects/underground.works/php-namespace-monkey/lib/php-namespace-monkey.js:63:36
    at FSReqWrap.oncomplete (fs.js:152:21)
```

### Commands

```
     -0:58.6.0 datatip:toggle (input.hidden-input)
     -0:54.4.0 core:move-right (input.hidden-input)
     -0:54 editor:select-to-beginning-of-word (input.hidden-input)
     -0:54 datatip:toggle (input.hidden-input)
     -0:53 core:save (input.hidden-input)
     -0:52.6.0 datatip:toggle (input.hidden-input)
     -0:52.6.0 pane:show-previous-item (input.hidden-input)
     -0:45.1.0 core:save (input.hidden-input)
     -0:44.7.0 editor:move-to-first-character-of-line (input.hidden-input)
  2x -0:44.7.0 datatip:toggle (input.hidden-input)
     -0:43.3.0 intentions:highlight (input.hidden-input)
     -0:43.3.0 datatip:toggle (input.hidden-input)
     -0:43.2.0 pane:show-previous-item (input.hidden-input)
     -0:29.3.0 core:save (input.hidden-input)
     -0:09.3.0 datatip:toggle (input.hidden-input)
     -0:09.1.0 pane:show-previous-item (input.hidden-input)
```

### Non-Core Packages

```
advanced-open-file 0.16.8 
atom-alignment 0.13.0 
atom-ide-ui 0.12.0 
autocomplete-php 0.3.7 
busy-signal 1.4.3 
color-picker 2.3.0 
emmet 2.4.3 
file-icons 2.1.21 
github-syntax 1.0.0 
hex 0.6.2 
hyperclick 0.0.0 
ide-php 0.7.14 
intentions 1.1.5 
language-vue 0.23.1 
linter 2.2.0 
linter-coffeescript 1.0.0 
linter-js-standard 5.0.0 
linter-php 1.5.1 
linter-sass-lint 1.8.3 
linter-ui-default 1.7.1 
merge-conflicts 1.4.5 
native-ui 0.26.2 
northem-light-atom-syntax 2.1.0 
octocat-syntax 2.2.2 
php-ide-serenata 4.1.2 
php-integrator-annotations 1.2.0 
php-integrator-autocomplete-plus 1.6.2 
php-integrator-refactoring 1.4.1 
php-namespace-monkey 0.2.0 
php-twig 4.0.0 
pigments 0.40.2 
pretty-json 2.0.1 
project-manager 3.3.6 
split-diff 1.5.2 
tabs-to-spaces 1.0.5 
teletype 0.13.3 
tidy-tabs 0.4.0 
vue2-autocomplete 0.1.0-alpha.4 
xml-formatter 0.11.0 
```

**Comment by itsgoingd** [comment]
Fixed in 0.2.1.
